name: New Issue
description: New Issue
body:
  - type: markdown
    attributes:
      value: |
        Dwmac project doesn't accept Issues directly. Please prefer GitHub Discussions. See: https://github.com/hillyu/Dwmac/issues/947
  - type: checkboxes
    id: checkbox
    attributes:
      label: 'Sanity check'
      options:
        - label: |
            I read https://github.com/hillyu/Dwmac/issues/947
          required: true
  - type: textarea
    id: body
    attributes:
      label: Body
      value: |
        YOUR ISSUE WILL BE IMMEDIATELY CLOSED BY BOT, DON'T OPEN NEW ISSUES DIRECTLY, USE DISCUSSIONS INSTEAD
    validations:
      required: true
