= dwmac-focus(1)
include::util/man-attributes.adoc[]
:manname: dwmac-focus
// tag::purpose[]
:manpurpose: Set focus to a window.
// end::purpose[]

// =========================================================== Synopsis
== Synopsis
[verse]
// tag::synopsis[]
dwmac focus [-h|--help] [--ignore-floating]
                [--boundaries <boundary>] [--boundaries-action <action>]
                (next|prev)
dwmac focus [-h|--help] --window-id <window-id>
dwmac focus [-h|--help] --index <index>

// end::synopsis[]

// =========================================================== Description
== Description

// tag::body[]
{manpurpose}

The `focus` command treats floating windows as part of the order of windows.
The technique eliminates the need for an additional binding for floating windows.
This behavior can be disabled with `--ignore-floating` flag.

`focus child|parent` isn't supported because the necessity of this operation is under the question.
https://github.com/hillyu/Dwmac/issues/5

// =========================================================== Options
include::util/conditional-options-header.adoc[]

-h, --help:: Print help

--boundaries <boundary>::
Defines focus boundaries. +
`<boundary>` possible values: `(workspace|all-monitors-outer-frame)`. +
The default is: `workspace`

--boundaries-action <action>::
Defines the behavior when requested to cross the `<boundary>`. +
`<action>` possible values: `(stop|fail|wrap-around-the-workspace|wrap-around-all-monitors)`. +
The default is: `stop`

--window-id <window-id>::
Focus the window with specified `<window-id>`

--index <index>::
Focus window by its 0-based index in the workspace window list.

--ignore-floating::
Don't perceive floating windows as part of the workspace window list.
It may be useful for more reliable scripting.

// =========================================================== Arguments
include::./util/conditional-arguments-header.adoc[]

(next|prev)::
Set focus to the next or previous window in the order (top-to-bottom and left-to-right) of windows in the current workspace.
In this mode, `--boundaries` must be `workspace` (the default) and `--boundaries-action` can be set to one of `(stop|fail|wrap-around-the-workspace)`.

// end::body[]

// =========================================================== Footer
include::util/man-footer.adoc[]